/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Greeter__factory } from "./Greeter__factory";
export { Receiver__factory } from "./Receiver__factory";
